### ISSUE TITLE
Reusing the app with different issuers

### ISSUE THREAD

**Issue by lanterno** [e-id-admin/eidch-pilot-android-wallet#1]
Hello, 
    Thanks for making this code open source. I'm currently testing ELFA project on my own machine to see how things work, however, right now I'm stuck at this screen. 
<img src="https://github.com/e-id-admin/eidch-pilot-android-wallet/assets/5256731/1c8a60d8-10c2-45e8-862e-f47a148353d8" width="300" alt="Screenshot_20240516-132724">

I was wondering how to make my local issuer known to the app?

**Comment by laudatioUno** [comment]
Hi lanterno

Thanks for reaching us. As we use the pilotWallet for our Use Case with the learners driver permit, we only allow our own issuer (and verifier) to connect from the app.
For that we implemented a certificate pinning and URL whitelisting in the code so we can be sure, that we connect to the correct counterparty.

You'll find the code for that in the file https://github.com/e-id-admin/eidch-pilot-android-wallet/blob/main/app/src/main/res/xml/network_security_config.xml

Here we pinned the certificate and the URL "astra.admin.ch".

So feel free to either add you own certificate or remove the check so you can connect to you own issuer.

Hope that helps and you can move forward.

**Comment by lanterno** [comment]
Hi @laudatioUno  This helps me very much. thanks a lot for the explanation!

**Comment by lanterno** [comment]
Hi @laudatioUno, I appreciate your assistance here, and I wanted to follow up with another question with regards to the same topic "different issuers and different schemas". 

Does the current version of the app only support only a specific schema type? Or does it expect specific fields to always be present? 

I've tried the standard ELFA schema named "sd_elfa_jwt" (defined [here](https://github.com/e-id-admin/eidch-pilot-elfa-base-infrastructure/blob/fbac0bacfd49ff9b6e7f5d532bc7089c63d3bab5/test_system/files/issuer_metadata.json#L5)) and this one works. 
However, trying any other schema from the same file, or my own custom schema seems to cause an error on the wallet.

**Comment by laudatioUno** [comment]
Hi @lanterno

The pilotWallet app is specifically designed to handle the eLFA SD-JWT exclusively, which is why other 'credentials_supported' are not compatible.
In the next edition of the wallet app, it will be able to handle all credentials, provided they are in the correct format (definition to be published).

For more detailed assistance, please post your JSON (including metadata and credentials), and we will analyze it.
